### ISSUE TITLE
USB-C Surge protecion

### ISSUE THREAD

**Issue by JmanNZ** [ElektorLabs/esp32-energymeter#2]
Hi
With D3 and D5 fitted the detected USB device is unrecognised. Removing D3 and D5 resolves the issue.
Burden resistors at 4.8 ohms this seems a little low would 6.8 ohms be a better value?

Thank you for the great project.

**Comment by Saad-Imtiaz** [comment]
Thank you for your feedback and for bringing this to my attention!

Regarding the issue with D3 and D5, it’s possible that these diodes might be affecting the USB communication, depending on their specific characteristics or placement in the circuit. I’ll investigate this further, but I’m glad to hear that removing them resolves the issue. If you prefer, you can leave them out if the device works as expected without them.

Burden resistors, 4.8 was selected as a compromise between sensitivity and power dissipation, but you're right – in some applications, it may come out to be 6.8, as it dissipates slightly less power. This value can be used when the case makes this value come out best for the measurement rather than 4.8. Sometimes burden resistor values may even be chosen based on whether the case suits that application where the sensitivity requirements for the measurement suggest this value.

Thanks again for your kind words and for trying the project!
